openapi: 3.0.3
info:
  title: ePrint API
  description: |
    API para la gestion de impresion y versiones de ePrint.
    Esta API permite obtener informacion del sistema, gestionar impresoras y enviar trabajos de impresion.
  version: 1.0.0
  contact:
    name: Soporte ePrint
    email: soporte@eprint.ejemplo.com
servers:
- url: http://localhost:19191
  description: Servidor de desarrollo local
tags:
  - name: General
    description: Operaciones generales de la plataforma
  - name: Administracion
    description: Operaciones de administracion del sistema
  - name: Impresion
    description: Operaciones relacionadas con impresoras y trabajos de impresion
paths:
  /:
    get:
      tags:
      - General
      summary: Pagina de inicio
      description: Devuelve la pagina de inicio con informacion de la plataforma
      operationId: home
      responses:
        "200":
          description: Pagina cargada correctamente
          content:
            text/html:
              schema:
                type: string
                description: Contenido HTML de la pagina about.html
            application/json:
              schema:
                $ref: '#/components/schemas/SystemInfo'
  /management/about:
    get:
      tags:
      - Administracion
      summary: Obtiene informacion del sistema
      description: Devuelve informacion sobre la configuracion y estado del sistema
      operationId: get_info
      responses:
        "200":
          description: Informacion obtenida con exito
          content:
            text/html:
              schema:
                type: string
                description: Contenido HTML de la pagina about.html
            application/json:
              schema:
                $ref: '#/components/schemas/SystemInfo'
        "500":
          description: Error al obtener la informacion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /management/print:
    get:
      tags:
      - Impresion
      - Administracion
      summary: Lista impresoras disponibles
      description: Devuelve una lista con las impresoras y si soportan impresion a doble cara
      operationId: printers
      responses:
        "200":
          description: Lista de impresoras obtenida con exito
          content:
            text/html:
              schema:
                type: string
                description: Contenido HTML de la pagina print.html
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Printer'
  /management/versions:
    get:
      tags:
      - Administracion
      summary: Obtiene las versiones de la aplicacion
      description: Lista de versiones con sus notas de lanzamiento
      operationId: get_versions
      responses:
        "200":
          description: Lista de versiones obtenida con exito
          content:
            text/html:
              schema:
                type: string
                description: Contenido HTML de la pagina version.html
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Version'
        "500":
          description: Error al obtener las versiones
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /management/docs:
    get:
      tags:
      - Administracion
      summary: Obtiene informacion de la API
      description: Devuelve la documentacion y estado de la API
      operationId: get_api
      responses:
        "200":
          description: Documentacion de la API obtenida con exito
          content:
            text/html:
              schema:
                type: string
                description: Contenido HTML de la pagina api-doc.html
  /printers:
    get:
      tags:
      - Impresion
      summary: Obtiene las impresoras disponibles en el equipo
      description: Lista de impresoras del equipo
      operationId: get_printers
      responses:
        "200":
          description: Lista de impresoras obtenida con exito
          content:
            text/html:
              schema:
                type: string
                description: Contenido HTML de la pagina impresoras.html
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Nombre de la impresora
  /printers/{printer_id}:
    post:
      tags:
      - Impresion
      summary: Enviar documento a la impresora
      description: Envia un archivo para ser impreso en una impresora especifica
      operationId: print_document
      parameters:
      - name: printer_id
        in: path
        description: ID (nombre) de la impresora de destino
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                copies:
                  type: string
                  description: Numero de copias a imprimir
                format:
                  type: string
                  format: binary
                  description: Archivo que se enviara a imprimir
                driver:
                  type: string
                  description: Configuracion del driver de impresion (modo de impresion, como a doble cara)
              required:
                - format
        required: true
      responses:
        "200":
          description: Documento enviado a imprimir con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Documento enviado a imprimir"
                  printer_id:
                    type: string
                    example: "HP LaserJet 1020"
        "400":
          description: No se ha subido ningun archivo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SystemInfo:
      type: object
      properties:
        LOGS:
          type: string
          description: Ruta de los logs del sistema
        PATH:
          type: string
          description: Ruta de instalacion
        PLATFORM:
          type: string
          description: Plataforma donde se ejecuta el servicio
        VERSION:
          type: string
          description: Version actual del software
    Printer:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la impresora
          example: "HP LaserJet 1020"
        duplex:
          type: boolean
          description: Indica si la impresora soporta impresion a doble cara
          example: true
    Version:
      type: object
      properties:
        version:
          type: string
          description: Numero de version
          example: "1.0.0"
        date:
          type: string
          format: date
          description: Fecha de lanzamiento
          example: "2023-01-15"
        changes:
          type: array
          description: Cambios incluidos en la version
          items:
            type: string
            example: "Anadido soporte para impresoras de red"
    Error:
      type: object
      properties:
        error:
          type: string
          description: Descripcion del error
          example: "No has enviado un fichero"
